### ISSUE TITLE
Koodikatselmointi

### ISSUE THREAD

**Issue by HenriikkaKarhuvaara** [emlai/JTurmite#1]
Palaute 6.1 15:25

Ehkä aihemäärittely voisi olla hieman pidempi, ilmavampi?
Aihemäärittelyssä ei taida olla esimerkkikäyttötapauksen kulkua
Sekvenssikaaviot puuttuivat vielä
Testejä ehkä aika niukasti, tosin en täysin varma pitäisikö kaikkea mitä ei ole testattu testata. Pit raportin mukaan kaikkea ei kuitenkaan ole testattu. Mutaatiot vain 68%

+ Hyvä ja selkeä "toteutettavat toiminnot” aihemäärittelyssä 
+ Selkeä ja kattava luokkakaavio
+ Hyvä pakkausrakenne
+ Selkeät nimet

**Comment by emlai** [comment]
Kiitti katselmoinnista! :+1:
